#!/bin/bash

declare cmd=$1
declare pluginName="test" # quick and dirty.

function __buildFile() {
    rojo build "config/${1}.project.json" --output "${1}.rbxl"
}

function __buildPlugin() {
    rojo build "config/dev.project.json" --plugin "${pluginName}.rbxmx"
}

function dev() {
    __buildFile "dev"
}

function test() {
    __buildFile "test"
}

function prod() {
    __buildFile "prod"
}

function plugin() {
    __buildPlugin
}

# must be identical to luau-lsp.sourcemap.generatorCommand
function sourcemap() {
    rojo sourcemap config/dev.project.json -o sourcemap.json --include-non-scripts --absolute
}

eval $cmd