#!/bin/bash

declare cmd=$1
declare scriptRunUnit="scripts/RunUnitTests.luau"

function __buildTestFile() {
    bash/build test
}

function __runTestFile() {
    run-in-roblox --place test.rbxl --script $1
}

function all() {
    echo "Not implemented"
}

function unit() {
    __buildTestFile && __runTestFile $scriptRunUnit
}

function integration() {
    echo "Not implemented"
}

function cloud() {
    echo "Not implemented"
}

if [[ ! -z $cmd ]]; then
    eval $cmd
else
    all
fi